@echo off
echo Stopping any running Node.js processes...
taskkill /f /im node.exe 2>nul

echo Clearing Next.js cache...
rmdir /s /q .next 2>nul

echo Clearing node_modules cache...
rmdir /s /q node_modules\.cache 2>nul

echo Starting development server...
npm run dev